
./sastantua 1 | head -n 1 | wc -c
./sastantua 2 | head -n 1 | wc -c
./sastantua 3 | head -n 1 | wc -c
./sastantua 4 | head -n 1 | wc -c
./sastantua 5 | head -n 1 | wc -c
./sastantua 6 | head -n 1 | wc -c
./sastantua 7 | head -n 1 | wc -c
./sastantua 8 | head -n 1 | wc -c
./sastantua 9 | head -n 1 | wc -c
./sastantua 10 | head -n 1 | wc -c
./sastantua 11 | head -n 1 | wc -c
./sastantua 12 | head -n 1 | wc -c
./sastantua 13 | head -n 1 | wc -c
./sastantua 14 | head -n 1 | wc -c
./sastantua 15 | head -n 1 | wc -c
./sastantua 16 | head -n 1 | wc -c
./sastantua 17 | head -n 1 | wc -c
./sastantua 18 | head -n 1 | wc -c
./sastantua 19 | head -n 1 | wc -c
./sastantua 20 | head -n 1 | wc -c